### ISSUE TITLE
splitTags doesn't work when there are '<' or '>' in tweet which are not part of any tag

### ISSUE THREAD

**Issue by mlowicki** [bcherry/twitter-text-js#2]
Input: Schöne Schriften -> http://bit.ly/Sdq0j
Output: Schöne Schriften -&lt; &gt;a href="http://bit.ly/Sdq0j"<http: bit.ly="" Sdq0j="">/a&lt;</http:>

**Comment by mlowicki** [comment]
The output is generated by twttr.txt.autoLink method

**Comment by bcherry** [comment]
< and > are always HTML-escaped in at Tweet-time, AFAIK.  Is your input example a real Tweet?  Otherwise, you'll have to HTML-escape the < and > before sending to auto-link.

**Comment by mlowicki** [comment]
Yup, escaping < and > first is the right solution here.
