### ISSUE TITLE
closure-compiler warning on line 283

### ISSUE THREAD

**Issue by jdub** [bcherry/twitter-text-js#3]
A minor nit, but twitter-text-js has a closer-compiler warning.

```
twitter-text.js:283: WARNING - Suspicious code. This code lacks side-effects. Is there a bug?
        options.htmlAttrs || "";
                          ^
```

I'm just worried that expected behaviour is missing as a result. :-)

Thanks!

**Comment by bcherry** [comment]
Ha, nice catch!  Fixed upstream in twitter/twitter-text-js
